name: "Cloudflare Purge Cache"
description: "Purge Cloudflare Zone Cache"
author: "Shane"
branding:
  icon: "cloud"
  color: "orange"

inputs:
  token:
    description: "Cloudflare API Token"
    required: true
  domains:
    description: "Cloudflare Domains to Purge"
    required: false
    default: ""
  zone:
    description: "For Backwards Compatibility ONLY"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
